trigger:
  branches:
    include:
    - main
  tags:
    include:
    - '*'
  paths:
    include:
    - '*'
    exclude:
    - .github/*
    - LICENSE.TXT
    - README.md

variables:
  - template: /eng/pipelines/common/variables.yml

parameters:
  - name: BuildEverything
    type: boolean
    default: false

stages:

  - template: common/device-tests.yml
    parameters:
      ${{ if or(parameters.BuildEverything, and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'devdiv'))) }}:
        androidApiLevels: [ 30, 29, 28, 27, 26, 25, 24, 23 ]
        # androidApiLevels: [ 30, 29, 28, 27, 26, 25, 24, 23, 22, 21 ] # fix the issue of getting the test results off
        iosVersions: [ 'latest', '14.5', '13.7', '12.4', '11.4' ]
      projects:
        - name: WeChat
          desc: WeChat
          android: $(System.DefaultWorkingDirectory)/test/Maui.Toolkit.WeChat/Maui.Toolkit.WeChat.DeviceTest/Maui.Toolkit.WeChat.DeviceTest.csproj
          ios: $(System.DefaultWorkingDirectory)/test/Maui.Toolkit.WeChat/Maui.Toolkit.WeChat.DeviceTest/Maui.Toolkit.WeChat.DeviceTest.csproj