name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-rc.1.21463.6
    
    - run: |
        $client.DownloadFile("https://aka.ms/download-jdk/microsoft-debugsymbols-11.0.12.7.1-windows-x64.zip", "$RUNNER_TEMP/microsoft-debugsymbols-11.0.12.7.1-windows-x64.zip")
    - uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/microsoft-debugsymbols-11.0.12.7.1-windows-x64.zip
        java-version: '11.0.0'
        architecture: x64
        
    - name: install workload
      run: dotnet workload install maui && dotnet workload install android-aot && dotnet workload install ios && dotnet workload install maccatalyst
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: .\unit-test.ps1
      working-directory: .\build
      shell: powershell
