name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# env:
#    DOTNETVERSION:  6.0.100-rc.2.21505.57
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    

    - name: Install workload
      shell: pwsh
      run: |
        & dotnet workload install maui
        & dotnet workload install android-aot
        & dotnet workload install ios
        & dotnet workload install maccatalyst
        & dotnet workload install tvos
        & dotnet workload install macos
        & dotnet workload install wasm-tools
        & dotnet workload install microsoft-net-sdk-emscripten
        
    - name: Install and Run maui-check Tool
      shell: pwsh
      run: |
        & dotnet tool update --global redth.net.maui.check
        & maui-check --ci --non-interactive --fix --force-dotnet --skip vswin --skip edgewebview2

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Android Emulator Runner
      # You may pin to the exact commit or the version.
      # uses: ReactiveCircus/android-emulator-runner@f71c6d1f84f7ccec53da56aa69c2b11fd56da227
      uses: ReactiveCircus/android-emulator-runner@v2.20.0
      with:
        # API level of the platform and system image - e.g. 23 for Android Marshmallow, 29 for Android 10
        api-level: 31
        # target of the system image - default, google_apis, google_apis_playstore, android-wear, android-wear-cn, android-tv or google-tv
        target: google_apis_playstore
        # CPU architecture of the system image - x86, x86_64 or arm64-v8a
        arch: x86_64
        # hardware profile used for creating the AVD - e.g. `Nexus 6`
        profile: Pixel 6
        # custom AVD name used for creating the Android Virtual Device
        avd-name: pixel_6_31
        # version of NDK to install - e.g. 21.0.6113669
      
    # - name: Start Android Emulator
    #  shell: pwsh
    #  run: |
    #    & cd 'C:\Program Files (x86)\Android\android-sdk\emulator\'
    #    & .\emulator.EXE -no-boot-anim -accel on -avd Android_Emulator_31 -prop monodroid.avdname=Android_Emulator_31
      
    # - name: Test
    #   run: .\unit-test.ps1
    #   working-directory: .\build
    #   shell: powershell
