name: build and unit test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: setup dotnet 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
          
      - name: setup dotnet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: maui-check
        shell: pwsh
        run: |
          & dotnet tool update --global redth.net.maui.check
          & maui-check --ci --non-interactive --fix --force-dotnet --skip vswin --skip xcode --skip edgewebview2 --skip androidemulator

      - name: build
        shell: pwsh
        run: dotnet build

      - name: unit test
        shell: pwsh
        run: ./script/unit-test.ps1
