name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    

    # - name: Install workload
    #  shell: pwsh
    #  run: |
    #    & dotnet workload install maui
    #    & dotnet workload install android-aot
    #    & dotnet workload install ios
    #    & dotnet workload install maccatalyst
        
    - name: Install and Run maui-check Tool
      shell: pwsh
      run: |
        & dotnet tool update --global redth.net.maui.check
        & maui-check --ci --non-interactive --fix --force-dotnet --skip vswin --skip xcode --skip edgewebview2 --skip android-emulator

    - name: Build
      shell: pwsh
      run: |
        & dotnet restore
        & dotnet build --no-restore -p:EmbedAssembliesIntoApk=true
        
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ./**/bin/Debug/net6.0-android/*-Signed.apk

    # - name: Test
    #   run: .\unit-test.ps1
    #   working-directory: .\build
    #   shell: powershell
