name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    DOTNETVERSION:  6.0.100-rc.1.21463.6
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    # open PR should remove need for the script SOON! https://github.com/microsoft/setup-msbuild/pull/56
    - name: Install Visual Studio Preview
      shell: pwsh
      run: powershell .\build\install-vs.ps1

    - name: Add msbuild to PATH
      shell: pwsh
      run: |
        dotnet tool update -g dotnet-vs
        & echo "$(vs where preview --prop=InstallationPath)\MSBuild\Current\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name:  install .NET 6 preview
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
        & .\dotnet-install.ps1 -Version ${{env.DOTNETVERSION}} -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
        & dotnet --list-sdks
        
    - name: Install workload
      shell: pwsh
      run: |
        & dotnet workload install android-aot
        & dotnet workload install ios
        & dotnet workload install maccatalyst
        & dotnet workload install maui
        & dotnet workload install wasm-tools
        
    - name: Install and Run maui-check Tool
      shell: pwsh
      run: |
        & dotnet tool update --global redth.net.maui.check
        & maui-check --ci --non-interactive --fix --force-dotnet --skip vswin --skip edgewebview2 --skip androidemulator --skip dotnetworkloads-6.0.100-rc.1.21458.32

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: .\unit-test.ps1
      working-directory: .\build
      shell: powershell
