name: build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup dotnet 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: setup dotnet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true

      - name: maui-check
        shell: pwsh
        run: |
          & dotnet tool update --global redth.net.maui.check
          & maui-check --ci --non-interactive --fix --force-dotnet --skip vswin --skip xcode --skip edgewebview2 --skip androidemulator

      - name: build
        shell: pwsh
        run: |
          & dotnet restore
          & dotnet build --no-restore -p:EmbedAssembliesIntoApk=true

      - name: unit test
        shell: pwsh
        run: ./script/device-test.ps1

      - uses: actions/upload-artifact@v2
        with:
          name: android-device-test
          path: |
            ./test/**/*.DeviceTest/bin/Debug/net6.0-android/*-Signed.apk
            ./script/device-test.ps1

  android-device-test:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        name: download artifact
        with:
          name: android-device-test
          path: ./

      - uses: actions/setup-dotnet@v1
        name: setup dotnet
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true

      - name: install XHarness
        shell: pwsh
        run: |
          & dotnet tool install Microsoft.DotNet.XHarness.CLI --global --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json --version "1.0.0-prerelease*"

      - name: run test
        uses: ReactiveCircus/android-emulator-runner@v2.20.0
        with:
          api-level: 30
          target: google_apis_playstore
          arch: x86_64
          profile: "pixel_4"
          avd-name: pixel_4_30
          disable-linux-hw-accel: false
          script: |
            pwsh ./script/device-test.ps1
