name: ios test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: setup dotnet 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: setup dotnet 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          include-prerelease: true

      - name: maui-check
        shell: pwsh
        run: |
          & dotnet tool update --global redth.net.maui.check
          & maui-check list
          & maui-check --ci --non-interactive --fix --force-dotnet --skip xcode --skip edgewebview2 --skip androidemulator

      - name: build
        shell: pwsh
        run: ./script/ios/build.ps1

      - name: install XHarness
        shell: pwsh
        run: |
          & dotnet tool install Microsoft.DotNet.XHarness.CLI --global --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json --version "1.0.0-prerelease*"

      - name: test
        shell: pwsh
        run: ./script/ios/test.ps1

      - uses: actions/upload-artifact@v2
        name: upload test results
        with:
          name: test-results
          path: ./out/
