name: test

on:
  workflow_run:
      workflows: ["build"]
      branches: [main]
      types: 
        - completed

jobs:
  test:
      runs-on: macos-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - uses: actions/download-artifact@v2
          name: download artifact
          with:
            name: artifact
            path: ./

        - uses: actions/setup-dotnet@v1
          name: setup dotnet
          with:
            dotnet-version: '6.0.x'
            include-prerelease: true
       
