name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    needs: build
    runs-on: macos-latest

    steps:
      - uses: actions/download-artifact@v2
        name: download artifact
        with:
          name: artifact
          path: ./
      
      - uses: actions/setup-dotnet@v1
        name: setup dotnet
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
       
